# Generated by Django 3.2.5 on 2021-07-16 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn_app', '0002_blocklist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dull',
            new_name='DullAPI',
        ),
    ]
